backend:
  name: github
  repo: johnpeart/dept-of-bad-ideas # your GitHub username and repository name, separated by a slash
  branch: master # optional, default value is "master"

site_url: https://badideas.podcast.johnpe.art
display_url: https://badideas.podcast.johnpe.art
logo_url: https://badideas.podcast.johnpe.art/assets/images/site/header-logo.svg

publish_mode: editorial_workflow

media_folder: "assets/images/posts" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # File name format
    extension: "md"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post", required: true}
    meta:
      - {label: "Publish date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss", required: true}
  - name: "episodes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Episodes" # Used in the UI, ie.: "New Post"
    folder: "_episodes" # The path to the folder where the documents are stored
    sort: "title:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # File name format
    extension: "md"
    editor:
      preview: false
    fields: # The fields each document in this collection have
        - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
        - {label: "Subtitle", name: "subtitle", widget: "string", required: true}
        - {label: "Summary", name: "summary", widget: "text", required: true}
        - {label: "Description", name: "description", widget: "text", required: true}
        - {label: "Body", name: "body", widget: "markdown", required: true}
        - {label: "Season", name: "season", widget: "number", valueType: "int", required: true}
        - {label: "Episode", name: "episode", widget: "number", valueType: "int", required: true}
        - {label: "Type", name: "type", widget: "select", options: ["trailer", "full"], default: "full", required: true}
        - {label: "Duration (minutes:seconds)", name: "duration", widget: "string", require: true}
        - {label: "Filesize (bytes)", name: "length", widget: "number", valueType: "int", require: true}
        - {label: "File URL", name: "file", widget: "string", require: true}
        - {label: "File type", name: "file_type", widget: "select", options: ["audio/x-m4a", "audio/mp3", "audio/mpeg", "video/quicktime", "video/mp4", "video/x-m4v", "appplication/pdf", "document/x-epub"], default: "audio/x-m4a", required: true}
        - {label: "Explicit", name: "explicit", widget: "select", options: ["yes", "no"], default: "no", required: true}
        - {label: "Block", name: "block", widget: "select", options: ["yes", "no"], default: "no", required: true}
    meta:
      - {label: "Layout", name: "layout", widget: "hidden", default: "episode", required: true}
      - {label: "Publish date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss", required: true}
  - name: "guest-guides" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Guest guides" # Used in the UI, ie.: "New Post"
    folder: "_guest-guides" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # File name format
    extension: "md"
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: true}
      - {label: "Permalink", name: "permalink", widget: "string", required: true}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post", required: true}
    meta:
      - {label: "Publish date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss", required: true}